### ISSUE TITLE
The updates to the metadata are not well-formed

### ISSUE THREAD

**Issue by naipotato** [zen-browser/flatpak#10]
Just look at [this commit](https://github.com/zen-browser/flatpak/commit/271e858c2e599e63ac551df38b865fe33d290904) to see that while it corresponds to the .37 update, it is adding the changelog for .35.

Additionally, the date does not follow the ISO 8601 format, and the releases are not being sorted correctly (from most recent to oldest).

**Comment by naipotato** [comment]
It seems that @bragefuglseth's work to improve the metadata in #7 was removed by a later commit.

Is it possible to access the code that automates the pushing of these commits to fix it?

**Comment by naipotato** [comment]
Ok I think I found it https://github.com/zen-browser/release-utils

**Comment by bragefuglseth** [comment]
Seems like the solution would be to update the metainfo in [flatpak-updates/index.ts](https://github.com/zen-browser/release-utils/blob/main/flatpak-updates/index.ts).

**Comment by naipotato** [comment]
Indeed. I'll try to send a PR later.

**Comment by naipotato** [comment]
Alright, I sent PRs zen-browser/release-utils#1 and #11 to fix this

**Comment by mauro-balades** [comment]
Should be fixed
