### ISSUE TITLE
Not updated on flathub

### ISSUE THREAD

**Issue by aadilayub** [zen-browser/flatpak#8]
The latest version on flathub is two weeks old, whereas the latest release in the repo is 8 hours ago.

**Comment by LeMoonStar** [comment]
The cause is a wrong ordering of the Releases section in the metadata XML-File - This is only happening since an automatic workflow took over the job of adding new releases.

I submitted a temporary fix with #13 - But the workflow itself has to be fixed as well.

**Comment by mauro-balades** [comment]
Should be fixed now, thanks!
